# Generated by Django 2.2.17 on 2020-12-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
